// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/generate-rpc-index.mjs; do not edit.
pub const SYNC_SERVICE: u32 = 1;
pub const ABORT_SYNC: u32 = 7;
pub const COLLECTION_SERVICE: u32 = 3;
pub const OPEN_COLLECTION: u32 = 0;
pub const CLOSE_COLLECTION: u32 = 1;
pub const MEDIA_SERVICE: u32 = 41;
pub const CHECK_MEDIA: u32 = 0;
pub const TRASH_MEDIA_FILES: u32 = 2;
