// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/generate-rpc-index.mjs; do not edit.
#pragma once
#include <cstdint>
constexpr uint32_t RPC_SYNC_SERVICE = 1;
constexpr uint32_t RPC_ABORT_SYNC = 7;
constexpr uint32_t RPC_COLLECTION_SERVICE = 3;
constexpr uint32_t RPC_OPEN_COLLECTION = 0;
constexpr uint32_t RPC_CLOSE_COLLECTION = 1;
constexpr uint32_t RPC_MEDIA_SERVICE = 41;
constexpr uint32_t RPC_CHECK_MEDIA = 0;
constexpr uint32_t RPC_TRASH_MEDIA_FILES = 2;
